/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LED_Red.h"
#include "LED_Red_aliases.h"
#include "LED_Green.h"
#include "LED_Green_aliases.h"
#include "LED_Blue.h"
#include "LED_Blue_aliases.h"
#include "Timer_1.h"
#include "Clock_1.h"
#include "isr_1.h"
#include "SCB_1.h"
#include "SCB_1_SPI_UART.h"
#include "SCB_1_PINS.h"
#include "SCB_1_SPI_UART_PVT.h"
#include "SCB_1_PVT.h"
#include "SCB_1_BOOT.h"
#include "SCB_1_SCBCLK.h"
#include "SCB_1_tx.h"
#include "SCB_1_tx_aliases.h"
#include "SCB_1_rx.h"
#include "SCB_1_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

